### ISSUE TITLE
Error "ModuleNotFoundError: No module named 'weldarray'" when using  python3.

### ISSUE THREAD

**Issue by surechen** [weld-project/weld#514]
Hello, thank you for your attention. I found the following error in using weld with python3. Does weld support Python 3 now?

Traceback (most recent call last):
  File "./testweld.py", line 5, in <module>
    from weldnumpy import weldarray
  File "/usr/local/lib/python3.6/dist-packages/weldnumpy/__init__.py", line 1, in <module>
    from weldarray import *
ModuleNotFoundError: No module named 'weldarray'

**Comment by sppalkia** [comment]
The old `python` directory distribution does not support Python 2.7. The new distribution in `weld-python` (which was still under active development when I was last working on this) supports Python 3+, but currently only has a Grizzly integration (no NumPy). The Grizzly `Series` API is similar to to NumPy, if that is a sufficient workaround for now.
